import type { FormEvent } from "react";
import { answerQuestion, type TwinAiResult, type TwinAiContext } from "../lib/twin-ai/analyzer";
import type { DiagnosticReport } from "../lib/diagnostics/evaluator";

type FleetReport = TwinAiResult & { highestRiskForklift: string; highestRiskScore: number };

export function TwinAiPanel({ report, diagnostics, result, question, error, onQuestionChange, onSubmit, onQuickQuestion, onFullReport, recordSummary, context }: { report: FleetReport; diagnostics: Record<string, DiagnosticReport>; result: TwinAiResult | null; question: string; error: string; onQuestionChange: (value: string) => void; onSubmit: () => void; onQuickQuestion: (question: string, result: TwinAiResult) => void; onFullReport: () => void; recordSummary: TwinAiResult; context: TwinAiContext }) {
  const display = result ?? report;
  const level = diagnostics[report.highestRiskForklift]?.level ?? "정상";
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); onSubmit(); };
  return <section className="twin-ai-panel panel" aria-label="Twin AI 분석 결과"><div className="panel-header"><div><span className="section-kicker">TWIN AI ANALYSIS</span><h2>Twin AI 분석 결과</h2></div><span className="panel-meta"><span className="live-dot" /> 실시간 분석</span></div><div className="twin-ai-headline"><div><span className="ai-label">현재 가장 위험한 장비</span><strong>{report.highestRiskForklift}</strong></div><span className={`status-badge report-level-${level}`}>{level} · {report.highestRiskScore}점</span></div><div className="twin-ai-result" aria-live="polite"><b>{display.title}</b><p>{display.answer}</p><div className="ai-evidence">{display.evidence.slice(0, 4).map((item) => <span key={item}>• {item}</span>)}</div><div className="ai-actions">{display.actions.slice(0, 2).map((item) => <span key={item}>권고 · {item}</span>)}</div></div><form className="twin-ai-question" onSubmit={submit}><label htmlFor="twin-ai-question-input">자연어 질문</label><div><input id="twin-ai-question-input" value={question} onChange={(event) => onQuestionChange(event.target.value)} placeholder="현재 가장 위험한 장비는?" /><button type="submit">분석</button></div>{error && <small role="alert">{error}</small>}</form><div className="ai-suggestions"><button type="button" onClick={() => onQuickQuestion("현재 가장 위험한 장비는?", answerQuestion("현재 가장 위험한 장비는?", context))}>현재 가장 위험한 장비는?</button><button type="button" onClick={() => onQuickQuestion("운행기록 요약해줘", recordSummary)}>운행기록 요약</button><button type="button" onClick={onFullReport}>전체 분석결과 생성</button></div></section>;
}

export function FleetReportModal({ report, recordSummary, onClose }: { report: FleetReport; recordSummary: TwinAiResult; onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onClick={onClose}><section className="report-modal fleet-report-modal" role="dialog" aria-modal="true" aria-labelledby="fleet-report-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="전체 리포트 닫기">×</button><span className="section-kicker">FLEET AI REPORT</span><h2 id="fleet-report-title">전체 분석결과 리포트</h2><div className="report-status"><span className="status-badge report-level-위험">최고 위험 {report.highestRiskForklift}</span><strong>{report.answer}</strong></div><div className="report-grid"><InfoRow label="AI 종합 의견" value={report.answer} /><InfoRow label="주요 분석 근거" value={report.evidence.join(" · ")} /><InfoRow label="운행기록 요약" value={recordSummary.answer} /><InfoRow label="권고 조치" value={report.actions.join(" · ")} /><InfoRow label="분석 기준" value="실시간 ECU 4개 입력값 · 더미 학습 프로필 기반 시연용 분석" /></div><button className="report-button" onClick={onClose}>확인</button></section></div>; }

function InfoRow({ label, value }: { label: string; value: string }) { return <div className="info-row"><span>{label}</span><strong>{value}</strong></div>; }
